// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Note = require("./Note.bs.js");
var Curry = require("rescript/lib/js/curry.js");

function gettimeofday(param) {
  return Date.now();
}

function sleep(ms) {
  return new Promise((function (resolve, _reject) {
                setTimeout((function (param) {
                        return resolve(undefined);
                      }), ms);
                
              }));
}

function localtime(time) {
  var seconds = new Date(time).getSeconds();
  var seconds$1 = seconds | 0;
  var minutes = new Date(time).getMinutes();
  var minutes$1 = minutes | 0;
  var hours = new Date(time).getHours();
  var hours$1 = hours | 0;
  return [
          seconds$1,
          minutes$1,
          hours$1
        ];
}

var UnixTime = {
  gettimeofday: gettimeofday,
  sleep: sleep,
  localtime: localtime
};

function pr_time(time) {
  var tm = localtime(time);
  console.log("\x1b[8D%02d:%02d:%02d%!", tm[2], tm[1], tm[0]);
  
}

var match = Note.E.create(undefined);

var send = match[1];

var e = match[0];

function run(param) {
  while(true) {
    Curry._2(send, undefined, Date.now());
    sleep(1);
  };
  
}

var log = Note.E.log(undefined, e, pr_time);

run(undefined);

var seconds = e;

exports.UnixTime = UnixTime;
exports.pr_time = pr_time;
exports.seconds = seconds;
exports.run = run;
exports.log = log;
/* match Not a pure module */
